DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    FIO VARCHAR(255)
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES (
  ID BIGSERIAL NOT NULL PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
     ID BIGSERIAL NOT NULL PRIMARY KEY,
	 AUTHOR_ID BIGINT,
     GENRE_ID BIGINT,
     NAME VARCHAR(255)
     );